### ISSUE TITLE
Convert controller inputs into driving commands

### ISSUE THREAD

**Issue by eleehiga** [GonzagaRobotics/ManualRoverControlSystem#10]
- maybe built in to driver/package
- complete when driving commands printed to screen from controller input
- commands: 
     - accelerate (RT) maybe spectrum based on intensity of the input
     -  deccelerate (LT) maybe spectrum based on intensity of the input
     - steer left/right (left stick) and should be a spectrum based on the input amount
- all converted into format useable by ROS (design this)

**Comment by zeintry** [comment]
If we are going to be building a web-app then the (standard gamepadAPI)[https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API] would be quite useful for this part.

**Comment by eleehiga** [comment]
By this commit https://github.com/GonzagaRobotics/ManualRoverControlSystem/commit/7e85c645c758ac521638a679c3753924b9354071
